import { defineConfig } from 'tsdown/config';

export default defineConfig({
    clean: true,
    dts: {
        banner: '// Generated by tsdown\n',
    },
    entry: ['src/index.ts'],
    external: ['cli-welcome', 'music-metadata'],
    format: 'esm',
    minify: true,
    outDir: 'dist',
    sourcemap: true,
    target: 'node20',
});
